server:
  port: 8201

spring:
  application:
    name: wsirius-admin
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring-boot-demo?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 1234567890

eureka:
  client:
    service-url:
#     defaultZone: ${EUREKA_DEFAULT_ZONE:localhost:8801/eureka/}
      defaultZone: http://localhost:8801/eureka/
    #default-zone: http://localhost:8801/eureka/
  instance:
    # 使用 IP 注册服务
    prefer-ip-address: true
    # 服务续约任务的调用间隔时间
    lease-renewal-interval-in-seconds: 30
    # 服务失效的时间
    lease-expiration-duration-in-seconds: 90
